### PR TITLE
Handle Twitch whispers

### PR DESCRIPTION
**Pull request by mrphlip**
Bunch of changes for Twitch whispers:
* Separate class that handles connection to the group chat servers and sends/receives whispers. Is mostly decoupled from the main bot, so in theory it can be replaced if the mechanism changes. As far as most of the bot's concerned, it's just sending and receiving private messages in the normal IRC manner.
* Users can now send commands via whisper, and get responses via whisper. For some commands this is disabled (specifically ones that modify bot state, like `!death`), though mods can use any command (but I'd prefer you don't). Doing so also avoids the anti-spam throttles.
* Commands that used to be throttled silently will now send notifications via whisper. Commands that used to be throttled publicly (eg `!death`) still will be.
* New command `!autostatus` that allows users to opt-in to receiving a status update when they join the channel. If the stream is live, this is essentially a summary of `!game`, `!show` and `!uptime`, while if the stream is offline it will send `!next`. Also includes `!advice`, because of course it does. For users who don't want the automatic message there's also just `!status` which sends that as a one-time message (but still as a whisper, to keep the chat from being spammed).
  * Note that Twitch join/part messages get sent in batches, so these automatic whispers may show up as much as a minute after you actually join the chat. I think that's still sufficient.

Whole thing seems a bit too major to just push live like I normally do, so here, I'll do the proper code-review thing for once.

### CODE REVIEW

**Comment by andreasots** [comment]
Due to [rate-limiting](https://discuss.dev.twitch.tv/t/whisper-rate-limiting/2836) I don't think we'll be able to do anything interesting with whispers.

I think that commands sent on the channel should get a response on the channel or a throttle notification that might be sent as a whisper. So `!status` and `!autostatus (off|on)?` should be recognised only as a whisper.

I think we should stop touching `irc.bot.SingleServerIRCBot` inappropriately in `LRRBot.start()` and write our own `Reactor` subclass. Some code from an old branch:

```python
class Reactor(irc.client.Reactor):
	def __init__(self):
		self.loop = asyncio.get_event_loop()
		super(Reactor, self).__init__(self.on_connect, self.on_disconnect, self.on_schedule)

	def on_connect(self, socket):
		self.loop.add_reader(socket, self.process_data, [socket])

	def on_disconnect(self, socket):
		self.loop.remove_reader(socket)

	def on_schedule(self, delay):
		self.loop.call_later(delay, self.process_timeout)
	
	def process_forever(self):
		self.loop.run_forever()

class LRRBot(irc.bot.SingleServerIRCBot):
        GAME_CHECK_INTERVAL = 5*60 # Only check the current game at most once every five minutes
        reactor_class = Reactor

        [...]

        def start(self):
                if hasattr(self.reactor.loop, 'create_unix_server'):
                        # TODO: To be more robust, the code really should have a way to shut this socket down
                        # when the bot exits... currently, it's assuming that there'll only be one LRRBot
                        # instance, that lasts the life of the program... which is true for now...
                        try:
                                os.unlink(config['socket_filename'])
                        except OSError:
                                if os.path.exists(config['socket_filename']):
                                        raise
                        promise = self.reactor.loop.create_unix_server(self.rpc_server, path=config['socket_filename'])
                        self.reactor.loop.run_until_complete(promise)
                super(LRRBot, self).start()

        [...]

        def on_connect(self, conn, event):
                """On connecting to the server, join our target channel"""
                # Don't fall over if the server sends something that's not real UTF-8
                conn.buffer.errors = "replace"
                log.info("Connected to server")
                self.twitchclient(conn, 3)
                conn.join("#%s" % config['channel'])
```

I think `LRRBot` and `TwitchWhisper` don't need to share a reactor instance as they share the same `asyncio` event loop.

**Comment by andreasots** [comment]
I knew I forgot something.

I think `utils.throttle` should be split to `cache` and `throttle`. `cache` would be a simple memoising decorator that would replace `utils.throttle` on functions that are not command handlers. `throttle` would have all the bells and whistles and only goes on command handlers. This would allow better defaults on `throttle`.

The reason I want `!status` and `!autostatus` to be only over whispers is that not everyone receives them. This should reduce complaints like "Why doesn't sempai notice me?".

**Comment by mrphlip** [comment]
Committed a few more changes, but I'm still playing with asyncio, once I get my head around that I'll look into the whisper-throttling thing.

I don't think we can specifically _react_ to the `whisper_limit_per_sec` `NOTICE`, since it doesn't give us any information about _which_ whisper was dropped... we could make some guesses and resend the latest one, but that doesn't sound ideal. I think a better bet is to try to avoid it happening, only send one whisper per second and queue the rest, and if that still hits the throttle sometime (as that linked twitch.tv post suggests can happen) then I guess that just happens.

**Comment by mrphlip** [comment]
OK, made the changes for asyncio. Still haven't done the whisper throttling just yet, I wanted to get this done first so I could do that throttling with asyncio, rather than doing it and then having to change it once I got this working...

**Comment by andreasots** [comment]
For the RPC server it might be worth looking at [asyncio's streams](https://docs.python.org/3/library/asyncio-stream.html). We might eventually want to use an asyncio-based IRC and Postgres libraries. There's already some amount of duplicated code (`swallow_errors{,_coro}`, `http_request{,_coro}`, and `api_request{,_coro}`).

**Comment by andreasots** [comment]
I tried to actually run this branch:
```python-backtrace
[2015-08-10 19:35:04,928] INFO:lrrbot:Bot startup
[2015-08-10 19:35:05,281] INFO:twitchsubs:Failed to get subscriber list from Twitch
[2015-08-10 19:35:05,792] INFO:lrrbot:Connected to server
[2015-08-10 19:35:06,532] INFO:lrrbot:Channel #qrpth joined
[2015-08-10 19:35:09,812] INFO:asyncio:poll 3.274 took 3.278 seconds
[2015-08-10 19:35:14,818] INFO:asyncio:poll 5.000 took 5.005 seconds
[2015-08-10 19:35:19,824] INFO:asyncio:poll 5.000 took 5.005 seconds
[2015-08-10 19:35:24,828] INFO:asyncio:poll 5.000 took 5.003 seconds
[2015-08-10 19:35:29,834] INFO:asyncio:poll 5.000 took 5.005 seconds
[2015-08-10 19:35:34,841] INFO:asyncio:poll 5.000 took 5.005 seconds
[2015-08-10 19:35:39,843] INFO:asyncio:poll 5.000 took 5.001 seconds
[2015-08-10 19:35:44,851] INFO:asyncio:poll 5.000 took 5.005 seconds
[2015-08-10 19:35:47,717] INFO:asyncio:poll 5.000 took 2.866 seconds
[2015-08-10 19:35:47,719] INFO:lrrbot:Command from qrpth: advice 
[2015-08-10 19:35:48,883] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticons failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:35:49,970] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticons failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:35:52,177] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticon_images failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:35:53,362] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticon_images failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:35:53,709] INFO:lrrbot:Command from qrpth: quote 
[2015-08-10 19:35:54,542] ERROR:chatlog:Error fetching emotes
Traceback (most recent call last):
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 290, in get_filtered_emotes
    emotesets = yield from get_twitch_emotes()
  File "/tmp/lrrbot/common/utils.py", line 141, in coro_wrapper
    self.lastreturn[params] = yield from coro_func(*args, **kwargs)
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 249, in get_twitch_emotes
    data = yield from utils.http_request_coro("https://api.twitch.tv/kraken/chat/emoticons")
  File "/tmp/lrrbot/common/utils.py", line 418, in http_request_coro
    raise firstex
  File "/tmp/lrrbot/common/utils.py", line 409, in http_request_coro
    return (yield from res.text())
AttributeError: 'HttpResponse' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 292, in get_filtered_emotes
    emotesets = yield from get_twitch_emotes_undocumented()
  File "/tmp/lrrbot/common/utils.py", line 141, in coro_wrapper
    self.lastreturn[params] = yield from coro_func(*args, **kwargs)
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 272, in get_twitch_emotes_undocumented
    data = yield from utils.http_request_coro("https://api.twitch.tv/kraken/chat/emoticon_images")
  File "/tmp/lrrbot/common/utils.py", line 418, in http_request_coro
    raise firstex
  File "/tmp/lrrbot/common/utils.py", line 409, in http_request_coro
    return (yield from res.text())
AttributeError: 'HttpResponse' object has no attribute 'text'
[2015-08-10 19:35:55,686] INFO:utils:Downloading https://api.twitch.tv/kraken/users/lrrbot failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:35:56,745] INFO:utils:Downloading https://api.twitch.tv/kraken/users/lrrbot failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:35:58,841] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticons failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:35:59,937] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticons failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:36:02,103] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticon_images failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:36:03,158] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticon_images failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:36:04,272] ERROR:chatlog:Error fetching emotes
Traceback (most recent call last):
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 290, in get_filtered_emotes
    emotesets = yield from get_twitch_emotes()
  File "/tmp/lrrbot/common/utils.py", line 141, in coro_wrapper
    self.lastreturn[params] = yield from coro_func(*args, **kwargs)
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 249, in get_twitch_emotes
    data = yield from utils.http_request_coro("https://api.twitch.tv/kraken/chat/emoticons")
  File "/tmp/lrrbot/common/utils.py", line 418, in http_request_coro
    raise firstex
  File "/tmp/lrrbot/common/utils.py", line 409, in http_request_coro
    return (yield from res.text())
AttributeError: 'HttpResponse' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 292, in get_filtered_emotes
    emotesets = yield from get_twitch_emotes_undocumented()
  File "/tmp/lrrbot/common/utils.py", line 141, in coro_wrapper
    self.lastreturn[params] = yield from coro_func(*args, **kwargs)
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 272, in get_twitch_emotes_undocumented
    data = yield from utils.http_request_coro("https://api.twitch.tv/kraken/chat/emoticon_images")
  File "/tmp/lrrbot/common/utils.py", line 418, in http_request_coro
    raise firstex
  File "/tmp/lrrbot/common/utils.py", line 409, in http_request_coro
    return (yield from res.text())
AttributeError: 'HttpResponse' object has no attribute 'text'
[2015-08-10 19:36:05,282] INFO:twitchsubs:Failed to get subscriber list from Twitch
[2015-08-10 19:36:05,403] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticons failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
^C[2015-08-10 19:36:06,159] INFO:lrrbot:Bot shutting down...
[2015-08-10 19:36:06,429] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticons failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:36:08,509] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticon_images failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:36:09,519] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticon_images failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
[2015-08-10 19:36:10,540] ERROR:chatlog:Error fetching emotes
Traceback (most recent call last):
  File "/tmp/lrrbot/lrrbot/__init__.py", line 131, in start
    self.loop.run_forever()
  File "/usr/lib64/python3.3/site-packages/asyncio/base_events.py", line 184, in run_forever
    self._run_once()
  File "/usr/lib64/python3.3/site-packages/asyncio/base_events.py", line 766, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib64/python3.3/site-packages/asyncio/selectors.py", line 424, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 290, in get_filtered_emotes
    emotesets = yield from get_twitch_emotes()
  File "/tmp/lrrbot/common/utils.py", line 141, in coro_wrapper
    self.lastreturn[params] = yield from coro_func(*args, **kwargs)
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 249, in get_twitch_emotes
    data = yield from utils.http_request_coro("https://api.twitch.tv/kraken/chat/emoticons")
  File "/tmp/lrrbot/common/utils.py", line 418, in http_request_coro
    raise firstex
  File "/tmp/lrrbot/common/utils.py", line 409, in http_request_coro
    return (yield from res.text())
AttributeError: 'HttpResponse' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 292, in get_filtered_emotes
    emotesets = yield from get_twitch_emotes_undocumented()
  File "/tmp/lrrbot/common/utils.py", line 141, in coro_wrapper
    self.lastreturn[params] = yield from coro_func(*args, **kwargs)
  File "/tmp/lrrbot/lrrbot/chatlog.py", line 272, in get_twitch_emotes_undocumented
    data = yield from utils.http_request_coro("https://api.twitch.tv/kraken/chat/emoticon_images")
  File "/tmp/lrrbot/common/utils.py", line 418, in http_request_coro
    raise firstex
  File "/tmp/lrrbot/common/utils.py", line 409, in http_request_coro
    return (yield from res.text())
AttributeError: 'HttpResponse' object has no attribute 'text'
[2015-08-10 19:36:11,610] INFO:utils:Downloading https://api.twitch.tv/kraken/chat/emoticons failed: AttributeError: 'HttpResponse' object has no attribute 'text', retrying...
^C[2015-08-10 19:36:12,052] INFO:lrrbot:Bot shutdown
```

**Comment by mrphlip** [comment]
Well, we're going to have that duplication regardless, as long as the webserver isn't using asyncio. I think switching out Flask for something asyncio-based just to avoid that duplication would be overkill at this point.

That said, it's possible that the other duplication of `swallow_errors_coro` could be avoided using a similar trick to what `throttle` is doing, so it can be applied to both coroutines and regular functions... only reason it isn't doing it already is I didn't figure out how to do it yet (I only got forced to figure it out since I didn't want to have to duplicate all of `_throttle_base`). I'll try to come up with a clean DRY way to do this that can be applied to all of the `utils` decorators.

I don't think there's much to be gained by moving to an asyncio postgres library... even after #89, it's not like we're going to have any particularly expensive queries we'd want to run non-blocking. With the exception of `chatlog.rebuild_all`, which barely counts.

Moving to an asyncio-based IRC library... maybe, I guess? I'd be hesitant to change something so fundamental about the bot. I'm not 100% opposed, but I'd have to be convinced the benefits are worthwhile... and right now what we have with the current library plugged into the asyncio event loop seems good enough.

As for that error: what version of aiohttp do you have installed? When I started working on this, I apparently had some ancient version of aiohttp lying around from god knows where, I had to upgrade it...

**Comment by andreasots** [comment]
> asyncio-based IRC library

When inevitably Twitch's web servers derp out again and stop in the middle of the TLS handshake it wouldn't interefere with the bot. I guess it's achievable with wrapping aiohttp calls in futures and setting callbacks on those futures.

> what version of aiohttp do you have installed?

Prehistoric. Upgraded and the error went away.

**Comment by mrphlip** [comment]
> When inevitably Twitch's web servers derp out again and stop in the middle of the TLS handshake it wouldn't interefere with the bot.

Sure, but we wouldn't need the bot to be asyncio-enabled to handle that. Make all the bot-command functions coroutines and make `on_message` dispatch with `asyncio.async` rather than calling the function directly. Shouldn't be too hard to get to the point where the bot only ever calls `http_request_coro` (while the webserver only ever calls `http_request`). Just requires yet more refactoring...

**Comment by andreasots** [comment]
Oh, right. This thing. Merge?

**Comment by mrphlip** [comment]
Finally got around to implementing those last couple of pieces. Check them out then we should be good to go I think.

**Comment by andreasots** [comment]
:confetti_ball:

**Pull request merged**
