### PR TITLE
Remove `utils.http_request`

### PR DESCRIPTION
**Pull request by andreasots**
* Replaces all uses of `utils.{api,http}_request` with `utils.{api,http}_request_coro`. The website and the card database builder continue to use `urllib` directly.
* Moves membership capability before `JOIN`. User list is now accurate*. `!viewers` throttle timeout lowered. No `JOIN` storm at startup because `NAMES` don't get converted into `JOIN`s.
* Rewrites the RPC server to use [streams](https://docs.python.org/3/library/asyncio-stream.html). All RPC handler functions are now coroutines.
* Removes `utils.{api,http}_request`.
* Renames `utils.{api,http}_request_coro` to `utils.{api,http}_request`.

\* Twitch, pls.

### CODE REVIEW

**Comment by mrphlip** [comment]
I'm still flicking through all the changes, looks good so far... but:
> The website and the card database builder continue to use `urllib` directly.
They probably shouldn't... that's probably a holdover from before we merged `common.utils`. Shouldn't we keep the non-coroutine `http_request` function around, and start using it from the website?

**Comment by andreasots** [comment]
To my knowledge the web stuff should be running single-threaded. If it wasn't the link spam page wouldn't work.

**Comment by mrphlip** [comment]
I think I may have been confused by 42f242dfed9cfd0ae2dffe924d66685cfd5572b5, which disabled a thing because it broke aio, where I misremembered it as disabling aio because it was broken by a thing. From the look of it, uwsgi doesn't even support threads at all unless you explicitly tell it to (and we don't).

**Comment by andreasots** [comment]
Fixed and rebased on top of master.

**Pull request closed without merging**
