### PR TITLE
Patreon login and notification overhaul

### PR DESCRIPTION
**Pull request by andreasots**
Work in progress: the code is a) a mess; b) untested; and c) not doing what the documentation below says it's doing. I'm aiming to finish this and merge it on Monday (2016-06-20) before CheckPoint+ because of [changes to resubscription notifications](https://discuss.dev.twitch.tv/t/important-re-subscription-change/6463).

cc @paul-lrr

### Notification changes
`newmessage` events replaced with:
* `twitch-subscription`: Subscription notification. Example: `{"name": "LRRbot", "count": 1, "time": "2016-06-11T22:09:02.812952+03:00"}`
  * `"name"`: name of the subscriber
  * `"avatar"`: avatar of the subscriber. Might be missing or `null`.
* `twitch-resubscription`: Resubscription notification. Example: `{"name": "LRRbot", "monthcount": 30, "message": "butts", "count": 1, "time": "2016-06-12T01:10:02.812952Z"}`
  * `"name"`, `"avatar"`: see `twitch-subscription`
  * `"monthcount"`: number of months subscribed
  * `"message"`: [message from the subscriber](https://discuss.dev.twitch.tv/t/important-re-subscription-change/6463)
* `twitch-message`: Twitch notification. Example: `{"message": "4 viewers resubscribed while you were away!", "count": 1, "time": "2016-06-12T01:10:02.812952Z"}`
  * `"message"`: message text
* `twitch-follow`: Follower notification. Example `{"name": "LRRbot", "count": 1, "time": "2016-06-11T22:09:02.812952+03:00"}`
  * `"name"`: name of the follower
  * `"avatar"`: avatar of the follower. Might be missing or `null`.
* `patreon-pledge`: Patreon pledge notification. Example: `{"patreon": {"full_name": "Corgi Pager"}, "twitch": null, "count": 4, "time": "2016-05-21T23:08:57.169924+03"}`
  * `"patreon"`: Patreon specific information
    * `"full_name"`: Patron full name
    * `"avatar"`: Avatar. Might be missing or `null`.
    * `"url"`: Patron's Patreon page
  * `"twitch"`: Twitch specific information. Might be missing or `null`.
    * `"name"`: Patron's Twitch name

Common fields:
* `"time"`: timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
* `"count"`: How many events of the same type as this event have occurred today.

`/notifications/updates` endpoint removed. Replaced with content negotiation on `/notifications/events` instead (i.e. set the `Accept` header to `application/json`). `after` parameter renamed to `last-event-id` to match the `Last-Event-Id` header in the [server-sent events spec](https://html.spec.whatwg.org/multipage/comms.html#server-sent-events). 

`/notifications/newmessage` endpoint removed.

`/api/stormcount` endpoint returns all counts in JSON format. Example: `{"twitch-subscription": 5, "twitch-resubscription": 20, "twitch-follow": 5, "patreon-pledge": 3, "twitch-message": 1}`

I couldn't come up with names for the new counters so they'll have randomly generated names.

### Patreon

Can link Patreon accounts and patrons with linked accounts can use sub-only commands. New pledges will be posted to the chat.

### CODE REVIEW

**Comment by andreasots** [comment]
One thing that is absent from the previous wall of text is the structure of JSON formatted `/notifications/events`:
```json
{
  "events": [
    {"event": "twitch-subscription", "data": {"name": "LRRbot", ...}, "id": 14549},
    ...
  ]
}
```

Other than that everything is ready for :rocket:!

**Comment by andreasots** [comment]
:rocket:!

**Comment by paul-lrr** [comment]
If I understand things correctly, with the new system, I just replace the `stream.addEventListener("newmessage",function(){...});` in the notifier with 3 different event listeners for the different types of notifications. (twitch-subscription,twitch-resubscription, and patreon-pledge). Is that correct?

Can I still send test notifications of the different types to help with my development process? If so what would be the new format for the request? (`curl http://lrrbot.mrphlip.com/notifications/newmessage --data "test=true&apipass=[dickbutt]&message=test+just+subscribed\!&channel=#loadingreadyrun&subuser=test&eventtime=1434015411&monthcount=9"` doesn't work anymore

**Comment by andreasots** [comment]
> Is that correct?

Yes.

> Can I still send test notifications of the different types to help with my development process?

No. I realised that allowing basically anyone inject arbitrary events is probably a bad idea. It may return in some form but for now you can use the `last-event-id` parameter or the `Last-Event-Id` header on `/notifications/events` to have the notifications start on a specific event. For example https://lrrbot.mrphlip.com/notifications/events?last-event-id=15804 starts with event 15805 which is a `twitch-resubscription` event.

**Comment by paul-lrr** [comment]
Is there a way to limit the responses from `notifications/events` to the last x events? To make it as simple as possible for the hosts, I made the subscription slideshow work off of usernames. The host inputs the first username they want to show and the slideshow grabs every sub notification since then. It does this by first getting the whole list of recent subs, searching it for the specified username and  getting that event's id, then making another request for everything after that id. At the moment, if I make a request for `notifications/events?list-event-id=0` it gets all 15,000 events, which is a ton of data to go through.

Sorry I didn't give you feedback on this right away, but I am hoping that you could make some changes to the format of the messages:
I think it would make more sense if the format of the responses for twitch vs patreon subs were consistent. At the moment, for a twitch sub the `data` field has the usename, mouthcount etc for the event, but in a Patreon pledge, the username is in a nested `patreon` field. I get that people might have both a patreon account and a twitch account, but it would be much simpler to parse if the person's "canonical" name was always in the same place. What if the Patreon notifications were more like:
```
{id:15799,event:patreon-pledge
data:{"time": "2016-06-20T21:17:09.890668+02:00","name": "qrpth", "avatar": [[avatar url]]", "url": "https://www.patreon.com/qrpth", "count": 1,"twitch": {[[null or twitch specific info]]} }
```
That way the username is always at `data.name` instead of having to check multiple places.

Also, this is not a big deal, but could the current total storm count (twitch subs, resubs and patreon pledges) be included with the message? I can check the `/api/stormcount` endpoint each time a sub comes in, but when the subs get backed up (like at the beginning of a checkpoint stream) that count gets out of sync with the notifier until the queue of notifications is finished.

**Comment by andreasots** [comment]
> Is there a way to limit the responses from `notifications/events` to the last x events?

Would you settle for some length of time instead? I.e `/notifications/events?interval=2+days` instead of `/notifications/events?limit=50`.

> Sorry I didn't give you feedback on this right away, but I am hoping that you could make some changes to the format of the messages: [...] That way the username is always at `data.name` instead of having to check multiple places.

If a `"name"` field is all you want I can add that. The description for that would be 'name used for the welcome message in chat' which for `patreon-pledge` is the Twitch name if it exists falling back to the Patreon name. Rearranging it completely like in the example would require changing the Javascript on the notification page which is currently difficult due to it being cached in browsers for an arbitrary length of time. I'm currently looking for a solution for that but don't expect it to happen for at least a month.

> Also, this is not a big deal, but could the current total storm count (twitch subs, resubs and patreon pledges) be included with the message? I can check the `/api/stormcount` endpoint each time a sub comes in, but when the subs get backed up (like at the beginning of a checkpoint stream) that count gets out of sync with the notifier until the queue of notifications is finished.

Either:

1. You want us to send all counters with all messages. I think that this is a waste of bandwith and disk space because you can fetch the counters at initialisation and update them as the events come in.
2. You want us to send the counters as they would be after the notifier has emptied the queue. This requires the negative stream delay device.

**Comment by paul-lrr** [comment]
I suggested the message limit because that is how it worked before, but length of time for the notifications would probably be even better than a strict message limit. :+1: 

The `name` field as "name used for welcome message" would be perfect. :+1: 

As I said, the counters thing isn't a big deal and as you point out, it would add a bunch of unnecessary bandwidth. I will use the existing storm count end point and track the notifications on the client side. :+1: 

That being said, if you work out how to do the negative stream delay thing, let me know :laughing:

**Comment by andreasots** [comment]
Done. The syntax for the `interval` parameter for `/notifications/events` is [whatever Postgres accepts](https://www.postgresql.org/docs/9.1/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT).

**Pull request merged**
