### PR TITLE
!live, !live register, !live CHANNEL

### PR DESCRIPTION
**Pull request by andreasots**
New commands to replace the shady link to leg_bot's decaying carcass.
* `!live`: Post the currenly live fanstreamers.
* `!live register`: Register your channel as a fanstreamer channel.
* `!live register CHANNEL`: Register CHANNEL as a fanstreamer channel.

Once a day `!live` checks for new channels in the calendar.

List of channels leg_bot was checking:
```json
[
    "only_scrubs_skip_leg_day",
    "rebelliousuno",
    "cantwearhats",
    "caffeinatedlemur",
    "durugai",
    "rucdoc",
    "vmkid",
    "dix",
    "admiralmemo",
    "mowdownjoe",
    "antitonic",
    "mastercheese",
    "polluxprocyon",
    "hpbraincase",
    "i_am_clockwork",
    "rerout343",
    "boofinka",
    "rednightmare7",
    "lambmower",
    "reilaoda",
    "themoosetetrino",
    "selenes92",
    "ranneko",
    "senstaku",
    "navarran",
    "erockhiphop",
    "uknit",
    "darkmorford",
    "mister_blue_sky",
    "tstodden",

    "seabats",
    "voxlunch",
    "james_lrr",
    "thepettersaga",
    "streambros",
    "darkmorford",
    "nullrush",
    "ekimekim3000",
    "raymonong",
    "lambmower",
    "sohnata",
    "nfstreams",
    "roastedgravy",
    "magistermystax",
    "mistahfixit",
    "j_s_bach",
    "lordwolfwood",
    "doctormia",
    "kinogami",
    "devinsanity",
    "charlofsweden",
    "cattleprodlynn",
    "roosevelt",
    "desertbus",
    "hiramas",
    "featherweight_",
    "rayfk",
    "themoatman",
    "metricos",
    "senstaku",
    "thefilthycasualplays",
    "uknit",
    "navarran",
    "upickvg",
    "malfunct",
    "catcard",
    "elcalen"
]
```
Channels that are on the calendar but not in leg_bot's list:
```json
[
    "v_nome",
    "survivor.tv",
    "survivor_tv",
    "doktornik",
    "koizom",
    "elementalalchemist",
    "kidspanner",
    "shadowchorus",
    "jwiley129",
    "rantling",
    "diserasta"
]
```

### CODE REVIEW

**Comment by mrphlip** [comment]
Is it possible to have the bot follow all the channels we're watching, and use [/streams/followed](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-streamsfollowed) to get the list of currently live streams, rather than checking them all one by one?

**Comment by andreasots** [comment]
I hadn't thought of that. Could you make LRRbot's token have the scopes `user_read` (for [`GET /streams/followed`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-streamsfollowed)) and `user_follows_edit` (for [`PUT /users/:user/follows/channels/:target`](https://github.com/justintv/Twitch-API/blob/master/v3_resources/follows.md#put-usersuserfollowschannelstarget))?

**Comment by mrphlip** [comment]
Done

**Comment by andreasots** [comment]
Pull request updated.

Channels that must be added manually because they are in leg_bot's list but not on the calendar:

```json
[
    "j_s_bach",
    "erockhiphop",
    "mister_blue_sky",
    "rerout343",
    "vmkid",
    "catcard",
    "malfunct",
    "devinsanity",
    "nfstreams",
    "hiramas",
    "lordwolfwood",
    "james_lrr",
    "metricos",
    "desertbus",
    "charlofsweden",
    "magistermystax",
    "navarran",
    "uknit",
    "ekimekim3000",
    "themoatman",
    "roastedgravy",
    "mistahfixit",
    "cattleprodlynn"
]
```

**Comment by andreasots** [comment]
Notice me, sempai!

**Comment by mrphlip** [comment]
Hey, I may have been busy the last couple weeks, but I swear I would've gotten to this... eventually...

**Pull request merged**
